# SPDX-FileCopyrightText: no
# SPDX-License-Identifier: CC0-1.0
#
# IndOS — Bootloader configuration
# Uses GRUB for widest compatibility (BIOS + UEFI)
---
efiBootLoader: "grub"

kernel: "/vmlinuz-linux-cachyos"
img: "/initramfs-linux-cachyos.img"
fallback: "/initramfs-linux-cachyos-fallback.img"

timeout: 5

grubInstall: "grub-install"
grubMkconfig: "grub-mkconfig"
grubCfg: "/boot/grub/grub.cfg"
grubProbe: "grub-probe"

efiDirectory: "/boot/efi"
