# SPDX-FileCopyrightText: no
# SPDX-License-Identifier: CC0-1.0
#
# IndOS — Finished page configuration
---
restartNowEnabled: true

restartNowChecked: true

restartNowCommand: "systemctl reboot"

notifyOnFinished: false
