# SPDX-FileCopyrightText: no
# SPDX-License-Identifier: CC0-1.0
#
# IndOS — fstab generation
---
mountOptions:
    default: defaults,noatime
    btrfs: defaults,noatime,compress=zstd:3,ssd,discard=async,space_cache=v2

ssdExtraMountOptions:
    btrfs: ssd,discard=async

crypttabOptions: luks
