# SPDX-FileCopyrightText: no
# SPDX-License-Identifier: CC0-1.0
#
# IndOS — Systemd services to enable on the installed system
---
services:
    - name: "NetworkManager"
      mandatory: true

    - name: "greetd"
      mandatory: true

    - name: "sshd"
      mandatory: false

    - name: "ananicy-cpp"
      mandatory: false

# No services to disable — we don't install DMs to fight with
disable: []
