title    OS 1 (LTS Kernel, %ARCH%, UEFI)
sort-key 02
linux    /%INSTALL_DIR%/boot/%ARCH%/vmlinuz-linux-cachyos-lts
initrd   /%INSTALL_DIR%/boot/%ARCH%/initramfs-linux-cachyos-lts.img
options  archisobasedir=%INSTALL_DIR% archisosearchuuid=%ARCHISO_UUID% quiet splash
