# SPDX-FileCopyrightText: no
# SPDX-License-Identifier: CC0-1.0
#
# IndOS Calamares Settings — Offline Installer (Niri-only)
# No DE chooser, no netinstall — Niri is the only compositor.
---
modules-search: [ local ]

instances:
- id:       indos_postinstall
  module:   shellprocess
  config:   shellprocess_indos.conf

sequence:
- show:
  - welcome
  - locale
  - keyboard
  - partition
  - users
  - summary
- exec:
  - partition
  - mount
  - unpackfs
  - machineid
  - fstab
  - locale
  - keyboard
  - localecfg
  - initcpiocfg
  - initcpio
  - removeuser
  - users
  - networkcfg
  - displaymanager
  - hwclock
  - bootloader
  - services-systemd
  - shellprocess@indos_postinstall
  - umount
- show:
  - finished

branding: indos

prompt-install: true

dont-chroot: false

oem-setup: false

disable-cancel: false

disable-cancel-during-exec: false

hide-back-and-next-during-exec: true

quit-at-end: false
